### ISSUE TITLE
Recommendation to get the mic to work

### ISSUE THREAD

**Issue by adayguerra** [armanijohnny/MacProMiniHackintosh#1]
Hi @armanijohnny,

first thanks for sharing, your EFI was a great start for my hackintosh. I had the same issue as you with the mic but I gave it VoodooHDA a try and actually the mic is working now. I have to push audio to the edge to check if there is any problem but so far I got it is working.

Feel free to delete this issue, as i didn't have other way to return you the favor about this github.

BR

**Comment by adayguerra** [comment]
it was just a comment so I close it

**Comment by armanijohnny** [comment]
Awesome @adayguerra thanks for the tip. I have not tried it yet but for sure over the next few days I'll give VoodooHDA a shot. It's not a big deal for me now as I use mainly my AirPods which works perfectly with no issues.
